apiVersion: v1
kind: Service
metadata:
  name: {{ include "casbin-mesh.fullname" . }}
  labels:
    {{- include "casbin-mesh.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      name: http
  selector:
    {{- include "casbin-mesh.selectorLabels" . | nindent 4 }}
